artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/ajaychaudhary8104/Datasets/raw/refs/heads/main/customer.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  unzip_data_dir: artifacts/data_ingestion

  all_schema:
    CustomerID: object
    Count: int64
    Country: object
    State: object
    City: object
    Zip Code: int64
    Lat Long: object
    Latitude: float64
    Longitude: float64
    Gender: object
    Senior Citizen: object
    Partner: object
    Dependents: object
    Tenure Months: int64
    Phone Service: object
    Multiple Lines: object
    Internet Service: object
    Online Security: object
    Online Backup: object
    Device Protection: object
    Tech Support: object
    Streaming TV: object
    Streaming Movies: object
    Contract: object
    Paperless Billing: object
    Payment Method: object
    Monthly Charges: float64
    Total Charges: object
    Churn Label: object
    Churn Value: int64
    Churn Score: int64
    CLTV: int64
    Churn Reason: object

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  raw_data_dir: artifacts/data_ingestion
  input_file_name: data.csv
  processed_data_file: artifacts/data_preprocessing/processed_data.csv
  drop_columns:
    - CustomerID
    - Count
    - Country
    - State
    - City
    - Zip Code
    - Lat Long
    - Churn Label
    - Churn Score
    - CLTV
    - Churn Reason   

data_transformation:
  root_dir: artifacts/data_transformation
  split_artifacts_dir: artifacts/data_transformation/split_data
  input_file_path: artifacts/data_preprocessing/processed_data.csv
  train_file_path: artifacts/data_transformation/split_data/train.csv
  validation_file_path: artifacts/data_transformation/split_data/validation.csv
  test_file_path: artifacts/data_transformation/split_data/test.csv
  test_size: 0.15
  validation_size: 0.15
  random_state: 42
  target_column: Churn Value 
  numerical_columns:
    - Tenure Months
    - Monthly Charges
    - Total Charges
    - Latitude
    - Longitude
    - Avg Monthly Spend
    - LongTermCustomer
    - HighMonthlyCharges
    - TotalServices
  categorical_columns:
    - Gender
    - Senior Citizen
    - Partner
    - Dependents
    - Phone Service
    - Multiple Lines
    - Internet Service
    - Online Security
    - Online Backup
    - Device Protection
    - Tech Support
    - Streaming TV
    - Streaming Movies
    - Contract
    - Paperless Billing
    - Payment Method

model_training:
  root_dir: artifacts/model_training
  train_file_path: artifacts/data_transformation/split_data/train.csv
  validation_file_path: artifacts/data_transformation/split_data/validation.csv
  model_file_path: artifacts/model_training/xgboost_model.pkl
  metrics_file_path: artifacts/model_training/model_metrics.json
  target_column: Churn Value

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/split_data/test.csv
  model_path: artifacts/model_training/xgboost_model.pkl
  metric_file_name: artifacts/model_evaluation/model_evaluation_metrics.json
  target_column: Churn Value
  mlflow_uri: https://dagshub.com/ajaychaudhary8104/End_to_End_ML_project_for_Customer_Churn_Prediction.mlflow


model_promotion:
  root_dir: artifacts/model_promotion
  metrics_file_path: artifacts/model_evaluation/model_evaluation_metrics.json
  model_file_path: artifacts/model_training/xgboost_model.pkl
  production_model_path: artifacts/model_promotion/production_model.pkl
  registered_model_name: XGBClassifier
  target_stage: Production
  mlflow_uri: https://dagshub.com/ajaychaudhary8104/End_to_End_ML_project_for_Customer_Churn_Prediction.mlflow
  promote_metric: f1
  promote_threshold: 0.77
  archive_existing_versions: true
  copy_local_model: true


model_inference:
  root_dir: artifacts/inference
  model_path: artifacts/model_training/xgboost_model.pkl
  input_data_path: artifacts/data_ingestion/data.csv
  prediction_output_path: artifacts/inference/predictions.csv
  target_column: Churn Value
  preprocessor_path: artifacts/data_transformation/preprocessor.pkl
  drop_columns:
    - CustomerID
    - Count
    - Country
    - State
    - City
    - Zip Code
    - Lat Long
    - Churn Label
    - Churn Score
    - CLTV
    - Churn Reason 